export const SEARCH_TYPES = {
  RESTAURANT: 'RESTAURANT',
  OTHERS: 'OTHERS'
}

export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE';
export const CHANGE_CITY_SEARCH_TEXT = 'CHANGE_CITY_SEARCH_TEXT';
export const CHANGE_PRIMARY_SEARCH_TEXT = 'CHANGE_PRIMARY_SEARCH_TEXT';
export const CHANGE_CITY_SEARCH_OPTIONS = 'CHANGE_CITY_SEARCH_OPTIONS';

export const SELECT_CITY = 'SELECT_CITY';
export const SELECT_RESTAURANT = 'SELECT_RESTAURANT';

export const ADD_RESTAURANTS = 'ADD_RESTAURANTS';

export const CLOSE_RESTAURANT_MODAL = 'CLOSE_RESTAURANT_MODAL';
