export const SEARCH_TYPES = {
  RESTAURANT: 'RESTAURANT',
  OTHERS: 'OTHERS'
}

export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE';
export const CHANGE_CITY_SEARCH_TEXT = 'CHANGE_CITY_SEARCH_TEXT';
export const CHANGE_PRIMARY_SEARCH_TEXT = 'CHANGE_PRIMARY_SEARCH_TEXT';
export const CHANGE_CITY_SEARCH_OPTIONS = 'CHANGE_CITY_SEARCH_OPTIONS';
export const SELECT_CITY = 'SELECT_CITY';
